name: "HoneyDwell"
description: "Follow the renovation of our Home"
email: contact@honeydwell.com
url: "http://localhost:4000"
twitter_username: honeydwell
paginate: 10
comments: true
markdown: kramdown

paginate_path: "/blog/page:num/"

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']
